[colors.bright]
black = "#444444"
blue = "#87afff"
cyan = "#87d7ff"
green = "#87d75f"
magenta = "#ff8700"
red = "#ff8700"
white = "#ffffff"
yellow = "#ffaf00"

[colors.normal]
black = "#303030"
blue = "#666666"
cyan = "#87d75f"
green = "#005f00"
magenta = "#d75f00"
red = "#d75f00"
white = "#ffffff"
yellow = "#ffaf00"

[colors.primary]
background = "#1c1c1c"
foreground = "#ffffff"

[cursor.style]
shape = "Block"

[font]
size = 11.0

[font.bold]
style = "Bold"

[font.normal]
family = "DejaVu Sans Mono for Powerline"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 1.0

[window.padding]
x = 8
y = 8

[keyboard]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
